### ISSUE TITLE
安卓客户端v1.0.5-v1.0.7均无法往服务器写，之前版本可以

### ISSUE THREAD

**Issue by yanquan2020** [ychisbest/AnyNote#4]
不知道是否是bug，v1.0.4版本及之前的原来都可以往服务器保存记录，之后的版本均无法保存记录了。
docker配置没动过。

**Comment by yanquan2020** [comment]
win客户端也一样的情况。。。

**Comment by ychisbest** [comment]
退出登录一次，登录时选https试试？

**Comment by ychisbest** [comment]
或者重新运行一下docker run命令，镜像有更新过

**Comment by yanquan2020** [comment]
镜像重新拉取了，现象依旧。具体表现为app右上角永远是红色感叹号，不会是绿色对勾，基本就是无法上传服务器。内外网（http/https）都试了。

**Comment by ychisbest** [comment]
可以url发我试一下吗？可以部署一个新的容器，\data指定空文件夹。

**Comment by yanquan2020** [comment]
> 可以url发我试一下吗？可以部署一个新的容器，\data指定空文件夹。

https://h3c-test.amdarm.us.kg
password

你试试看

**Comment by ychisbest** [comment]
镜像后面改成了 anynoteofficial/anynote:latest 了，重新pull一下试试。
忘了删掉原来的ych8398527/anynote:1.0了，那个没更新了

**Comment by yanquan2020** [comment]
> 镜像后面改成了 anynoteofficial/anynote:latest 了，重新pull一下试试。 忘了删掉原来的ych8398527/anynote:1.0了，那个没更新了

换成这个anynoteofficial/anynote镜像，可以了
